// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_uiimgdog;
lv_obj_t * uic_uilabelright;
lv_obj_t * uic_uilabelfwd;
lv_obj_t * uic_uilabelleft;
lv_obj_t * uic_uilabelbrake;
lv_obj_t * uic_Image;
lv_obj_t * ui_Image = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_uilabelbrake = NULL;
lv_obj_t * ui_uilabelleft = NULL;
lv_obj_t * ui_uilabelfwd = NULL;
lv_obj_t * ui_uilabelright = NULL;
lv_obj_t * ui_uiimgdog = NULL;
// event funtions

// build funtions

void ui_Image_screen_init(void)
{
    ui_Image = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Image);
    lv_img_set_src(ui_Image1, &ui_img_gforcegauge_asset_1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 520
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 520
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 125);

    ui_uilabelbrake = lv_label_create(ui_Image);
    lv_obj_set_width(ui_uilabelbrake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uilabelbrake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uilabelbrake, 0);
    lv_obj_set_y(ui_uilabelbrake, -100);
    lv_obj_set_align(ui_uilabelbrake, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uilabelbrake, "0.0");
    lv_obj_set_style_text_font(ui_uilabelbrake, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uilabelleft = lv_label_create(ui_Image);
    lv_obj_set_width(ui_uilabelleft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uilabelleft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uilabelleft, -100);
    lv_obj_set_y(ui_uilabelleft, 0);
    lv_obj_set_align(ui_uilabelleft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uilabelleft, "0.0");
    lv_obj_set_style_text_font(ui_uilabelleft, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uilabelfwd = lv_label_create(ui_Image);
    lv_obj_set_width(ui_uilabelfwd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uilabelfwd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uilabelfwd, 0);
    lv_obj_set_y(ui_uilabelfwd, 100);
    lv_obj_set_align(ui_uilabelfwd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uilabelfwd, "0.0");
    lv_obj_set_style_text_font(ui_uilabelfwd, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uilabelright = lv_label_create(ui_Image);
    lv_obj_set_x(ui_uilabelright, 100);
    lv_obj_set_y(ui_uilabelright, 0);
    lv_obj_set_align(ui_uilabelright, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uilabelright, "0.0");
    lv_obj_set_style_text_font(ui_uilabelright, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiimgdog = lv_img_create(ui_Image);
    lv_img_set_src(ui_uiimgdog, &ui_img_dot_asset_2_png);
    lv_obj_set_width(ui_uiimgdog, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_uiimgdog, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_uiimgdog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiimgdog, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiimgdog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_uiimgdog, 150);

    uic_Image = ui_Image;
    uic_uilabelbrake = ui_uilabelbrake;
    uic_uilabelleft = ui_uilabelleft;
    uic_uilabelfwd = ui_uilabelfwd;
    uic_uilabelright = ui_uilabelright;
    uic_uiimgdog = ui_uiimgdog;

}

void ui_Image_screen_destroy(void)
{
    if(ui_Image) lv_obj_del(ui_Image);

    // NULL screen variables
    uic_Image = NULL;
    ui_Image = NULL;
    ui_Image1 = NULL;
    uic_uilabelbrake = NULL;
    ui_uilabelbrake = NULL;
    uic_uilabelleft = NULL;
    ui_uilabelleft = NULL;
    uic_uilabelfwd = NULL;
    ui_uilabelfwd = NULL;
    uic_uilabelright = NULL;
    ui_uilabelright = NULL;
    uic_uiimgdog = NULL;
    ui_uiimgdog = NULL;

}
